---
title: "ReporteT02"
author: "Jessica Garcia, Manuel Rivera, Axel Rodriguez"
date: "2023-02-10"
output:
  pdf_document: 
    toc: true
    toc_depth: 3
    number_sections: true
  html_document:
    toc: true # table of content true
    toc_float: yes
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
---


# Para _E.coli_

## Usando bwa para _indexar_ el genoma de _E.coli_

Se comienza por crear un entorno de trabajo con los archivos necesarios para la practica

```bash
# Se crea un screen de la practica para poder recurrir a los comandos en distintos momentos
screen -r -D Alignment

# Pasar archivos que se necesitan a carpeta de trabajo
cp -r /mnt/Timina/bioinfoII/data/alignment/ /mnt/Timina/bioinfoII/arodriguez/alignment

# Cargar modulos
module load bwa/0.7.15
module load fastqc/0.11.3
module load samtools/1.9

```
Para este alineamiento, los archivos `Escherichia_coli_K12_MG1655.fasta` y `SRX189773_FNR_ChIP.fastq` se refieren al genoma de referencia y a las lecturas del experimento, respectivamente.


## Usando bwa para _indexar_ el genoma de _E.coli_

Los indices permiten a las herramientas de alineacion (STAR, BWA, minimap2) recuperar rápida y eficientemente la información de la secuencia de referencia, ahorrando tiempo y memoria.

```bash
bwa index -p E_index -a bwtsw Escherichia_coli_K12_MG1655.fastax
```

- `-p` indica el prefijo de los archivos generados
- `-a` elige alguno de los algoritmos de indexacion de bwa (en este caso bwtsw).

## Alinea las lecturas de un experimento de FNR Chip-seq 

```bash
bwa aln E_index SRX189773_FNR_ChIP.fastq > Escherichia.sai
bwa samse E_index Escherichia.sai SRX189773_FNR_ChIP.fastq > Escherichia.sam
```

- `bwa aln` alinea el archivo de entrada de datos de secuencia con el genoma de referencia y produce un archivo `*.sai` de todos los posibles candidatos.
- `samse` genera los alineamientos en un archivo `.sam` dado un archivo `.sai` y el prefijo dado en `aln` (`E_index` en este caso). Se utiliza en lecturas **********single-end**********.

### Otras alternativas 

```bash
# OPcion 1
bwa aln E_index SRX189773_FNR_ChIP.fastq > Escherichia.bwa
bwa samse E_index Escherichia.bwa SRX189773_FNR_ChIP.fastq > Escherichia.sam

# Opcion 2
bwa mem E_index SRX189773_FNR_ChIP.fastq > Escherichia.sam
```

- `mem` se refiere al algoritmo mem, que es uno de los tres algoritmos proporcionados por BWA. Realiza la alineación local y produce alineaciones para diferentes partes de la secuencia de consulta.

## Analisis de calidad del alineamiento

```bash
# Opcion 1
samtools view -H Escherichia.sam | less -S
# Opcion 2
samtools stats Escherichia.sam | grep 'SN'
# Opcion 3
samtools flagstat Escherichia.sam
```
### Radio de Mapeo (*Mapping rate*)

### DRadio de duplicacion (*Duplication rate*)

### Contenido de GC vs Profundidad de Lectura

### Indeles por ciclo (*Indels by cycle*)

# Para *Mus musculus*

## Control de calidad de las secuencias crudas (*raw sequences*)

__FastQC__, es una herramienta utilizada para proporcionar una visión general de las métricas básicas de control de calidad para los datos de secuenciación de próxima generación sin procesar. En este caso, los datos crudos de las lecturas se encuentran en el archivo `mus_musculus_CEBPA_liver_ERR005132.fastq.gz`

```bash
fastqc mus_musculus_CEBPA_liver_ERR005132.fastq.gz
```

### Per Base Sequence Quality

### Per Sequence Quality Scores

### Per Base Sequence Content

### Per Base GC Content

### Per Sequence GC Content

### Per Base N Content

### Sequence Length Distribution

### Duplicate Sequences

### Overrepresented Kmers

## Index para el genoma de *Mus musculus*

Los archivos de *indexación* y el genoma de referencia se encuentran en el siguiente directorio del cluster:

```bash
/mnt/Archives/genome/mouse/mm10/UCSC/bwa-0.7.15-index/index
```

Donde `mm10.fa` se refiere al genoma de referencia (Genome Reference Consortium Mouse Build 38 (GCA_000001635.2)); mientras que `mm10.fa.amb`, `mm10.fa.ann`, `mm10.fa.bwt`, `mm10.fa.pac`, y `mm10.fa.sa` son los archivos del *index*.

## Alineacion del genoma de raton de un experimento ChiP-seq utilizando bwa

Antes de realizar el alineamiento, verificamos el tamaño de los archivos 

```bash
cd /mnt/Archives/genome/mouse/mm10/UCSC/bwa-0.7.15-index/index
ls -lh
```

Teniendo en cuenta el tamaño de los archivos tanto del genoma de referencia *Mus musculus* como de los datos de ChIP-seq de CEBPA, la memoria disponible para las sesiones de `qlogin` podría no ser suficiente, y probablemente haría que el proceso se suspendiera indefinidamente. Por lo tanto se generó un script sge llamadao `MusculusAlignment.sge`, el cual contiene lo siguiente:

```bash
#!/bin/bash
#
# Use Current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j n
#
# Run job through bash shell
#$ -S /bin/bash
#
# You can edit the script since this line
#
# Your job name
#$ -N MusculusAlignment
#
# Send an email after the job has finished
#$ -m e
#$ -M axelrdz5205@gmail.com
#
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
module load bwa/0.7.15
#
# Write your commands in the next line

# Generar alineamiento
# trabajando en /mnt/Timina/bioinfoII/arodriguez/alignment/Musmusculus/
bwa mem -M -t 8 /mnt/Archives/genome/mouse/mm10/UCSC/bwa-0.7.15-index/index/mm10.fa ./mus_musculus_CEBPA_liver_ERR005132.fastq.gz > Mus_alg.sam

# -M deja la mejor (más larga) alineación para una lectura como alineación primaria y alineaciones adicionales para la lectura como secundaria
# -t indica el número de núcleos de procesador utilizados para hacer la alineación
```

## Analisis decalidad del alineamiento

```bash
# Opcion 1
samtools view -H Mus_alg.sam | less -S
# Opcion 2
samtools stats Mus_alg.sam | grep 'SN'
# Opcion 3
samtools flagstat Mus_alg.sam
```

Nota: los archivos de alineamiento se enceuntran en la carpeta `/mnt/Timina/bioinfoII/arodriguez/alignment/Musmusculus`

